from .lw_resnet import ResNet56_cifar
from .lw_resnet import ResNet56_cifar_w0_5
from .lw_resnet import ResNet56_cifar_w2
from .lw_resnet import ResNet20_cifar,ResNet20_cifarF,ResNet18_TinyImageNet,ResNet34_TinyImageNet,ResNet56_TinyImageNet
from .lenet import Lenet
from .alexnet import AlexNet
from .vit  import  vit_32,vit_64,vit_giant_patch14
from .MobileNetV3 import MobileNetV3_Small,MobileNetV3_Large
from .Regnet import RegNet
from .efficientnet import effnetv2_s
from .vit_con import vit_base_patch16_224_with_mynet,vit_huge_patch14_224_with_mynet,vit_tiny_patch16_224_with_mynet
